export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_TRENDING_NEWS = "ADD_TRENDING_NEWS";
export const ADD_TRENDING_NEWS_ACC_CATEGORY = "ADD_TRENDING_NEWS_ACC_CATEGORY";
export const ADD_NEWS = "ADD_NEWS";
